name: "Setup sbt installer"
description: "Sets up sbt runner script"
inputs:
  sbt-runner-version:
    description: "The runner version (The actual version is controlled via project/build.properties)"
    required: true
    default: 1.10.4
runs:
  using: "composite"
  steps:
    - name: Set up cache paths
      id: cache-paths
      shell: bash
      run: |
        echo "sbt_toolpath=$RUNNER_TOOL_CACHE/sbt/${{ inputs.sbt-runner-version }}" >> "$GITHUB_OUTPUT"
        echo "sbt_downloadpath=$RUNNER_TEMP/_sbt" >> "$GITHUB_OUTPUT"
    - name: Check Tool Cache
      id: cache-tool-dir
      shell: bash
      run: |
        mkdir -p "${{ steps.cache-paths.outputs.sbt_toolpath }}"
        if [ -f "${{ steps.cache-paths.outputs.sbt_toolpath }}/sbt/bin/sbt" ]; then
          echo "cache-hit=true" >> "$GITHUB_OUTPUT"
        else
          echo "cache-hit=false" >> "$GITHUB_OUTPUT"
        fi
    - name: Cache sbt distribution
      id: cache-dir
      if: steps.cache-tool-dir.outputs.cache-hit != 'true'
      uses: actions/cache@v4
      with:
        path: ${{ steps.cache-paths.outputs.sbt_toolpath }}
        key: ${{ runner.os }}-sbt-${{ inputs.sbt-runner-version }}-1.1.4
    - name: "Download and Install sbt"
      shell: bash
      env:
        SBT_RUNNER_VERSION: ${{ inputs.sbt-runner-version }}
      if: steps.cache-tool-dir.outputs.cache-hit != 'true' && steps.cache-dir.outputs.cache-hit != 'true'
      run: |
        mkdir -p "${{ steps.cache-paths.outputs.sbt_downloadpath }}"
        curl -sL "https://github.com/sbt/sbt/releases/download/v$SBT_RUNNER_VERSION/sbt-$SBT_RUNNER_VERSION.zip" > \
          "${{ steps.cache-paths.outputs.sbt_downloadpath }}/sbt-$SBT_RUNNER_VERSION.zip"

        pushd "${{ steps.cache-paths.outputs.sbt_downloadpath }}"
        unzip -o "sbt-${{ inputs.sbt-runner-version }}.zip" -d "${{ steps.cache-paths.outputs.sbt_toolpath }}"
        popd
    - name: "Setup PATH"
      shell: bash
      run: |
        pushd "${{ steps.cache-paths.outputs.sbt_toolpath }}"
        ls sbt/bin/sbt
        echo "$PWD/sbt/bin" >> "$GITHUB_PATH"
        popd
